name: build-linux

on:
  push:
    branches: [main]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install PySide6 pyqtdarktheme

      - name: Import check
        run: python - <<'PY'
from PySide6 import QtWidgets  # import sanity
import qdarktheme              # module name is qdarktheme
print("Imports OK")
PY

      - name: Lint py
        run: |
          pip install pyflakes
          pyflakes panek_video_program.py || true
