- name: Python venv
     run: |
       python3 -m venv --system-site-packages .venv
       . .venv/bin/activate
       python -m pip install -U pip wheel
       python -m pip install PySide6 qdarktheme  # Updated for v2
