name: Build Linux

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  linux:
    name: Linux build and smoke test
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive
      QT_QPA_PLATFORM: offscreen
      PANEK_CI: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show workspace
        shell: bash
        run: |
          set -euo pipefail
          pwd
          ls -la

      - name: System deps
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip python3-venv ffmpeg kdialog zenity xvfb libgl1
          python3 -V || true
          ffmpeg -version || true
          kdialog --version || true
          zenity --version || true

      - name: Python venv
        shell: bash
        run: |
          set -euo pipefail
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi

      - name: Optional smoke import
        shell: bash
        run: |
          set -euo pipefail
          . .venv/bin/activate
          if [ -f panek_video_program.py ]; then
            python -c "import os,importlib.util as iu; os.environ['PANEK_CI']='1'; p='panek_video_program.py'; s=iu.spec_from_file_location('app',p); m=iu.module_from_spec(s); s.loader.exec_module(m); print('Import OK')"
          else
            echo "panek_video_program.py not found, skipping"
          fi
